# ---------------------------------------------------------------------------
# Buffer_mb.py
# Created on: 2013-01-15 01:51:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Freeways = "C:\\Users\\Jon\\Dropbox\\GEOG656\\Lab5\\all\\SanDiego.gdb\\Freeways"
FreeBuffer1000 = "C:\\Users\\Jon\\Documents\\ArcGIS\\Default.gdb\\FreeBuffer1000"

# Process: Buffer
arcpy.Buffer_analysis(Freeways, FreeBuffer1000, "1000 Feet", "FULL", "ROUND", "NONE", "")

